services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: votosalcaldia_app
    container_name: votosalcaldia_app
    ports:
      - "${OUTPUT_PORT:-8091}:80"
    volumes:
      - .:/var/www/html
      - votaciones_vendor:/var/www/html/vendor
      - votaciones_public:/var/www/html/public
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c", "/docker/entrypoint.sh"]
    # restart: unless-stopped  # Uncomment prod

  node:
    image: node:20-alpine
    container_name: votosalcaldia_node
    working_dir: /app
    volumes:
      - .:/app:cached  # Hot reload
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    # profiles: ["dev"]  # docker compose --profile dev up node

volumes:
  votaciones_vendor:
  votaciones_public: